### ISSUE TITLE
Ajout des nouvelles mailles officielles de l'INPN (M2, M20, M50)

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/RefGeo#24]
Le [référentiel de sensibilité a évolué en 2022](https://inpn.mnhn.fr/telechargement/referentiels/sensibilite) avec notamment un changement sur les géométries de dégradation, délaissant les limites administratives (communes, départements) pour privilégier un floutage surfacique s'appuyant sur des mailles. Je propose d'ajouter au module `RefGeo` les 3 fichiers de migrations pour ajouter respectivement les mailles:

- 2x2km
- 20x20km
- 50x50km

@PnX-SI/pnx-si-admin, Quelle procédure pour l'ajout des fichiers de données pour ces mailles ? cf. https://geonature.fr/data/inpn/layers/2020/. Je vous envoie les 3 fichiers `csv.xz` et vous les mettez sur votre serveur?  

**Extrait du guide technique**

![Screenshot 2024-04-23 at 16-22-51 Ichter_et_al_2022 pdf](https://github.com/PnX-SI/RefGeo/assets/22891423/45dc2bc5-ffbf-4279-82f0-d5690ba2960b)

**Comment by camillemonchicourt** [comment]
On prévoyait d'attendre que l'INPN publie ces nouvelles mailles.
Mais si ça devient important d'en disposer dans GeoNature, en effet, on peut le faire nous-mêmes et si tu les as faites sur le même référentiel que celles existantes dans l'INPN, on pourrait publier ça en effet !

**Comment by lpofredc** [comment]
Elles sont justement publiées par l'INPN: https://inpn.mnhn.fr/telechargement/cartes-et-information-geographique

**Comment by tsevere-cenpaca** [comment]
Dans la même logique, est-il envisageable d’ajouter la maille 70km qui correspond en gros à la surface 5000 km2 ?
