### ISSUE TITLE
Améliorer la recherche des noms des communes pour la Synthèse

### ISSUE THREAD

**Issue by ch-cbna** [PnX-SI/RefGeo#31]
Voir [#531](https://github.com/PnX-SI/GeoNature-atlas/issues/531) 

**Question** : Est-ce que le nom que l'on commence à saisir lorsqu'on cherche une commune à noms composés lance une recherche commençant par le nom saisi (option A), ou est-ce qu'on souhaite que le nom saisi fasse partie du nom de la commune recherchée, indépendamment de sa place dans le nom composé de la commune (option B) ? 

En d'autre termes, plus techniques : 

- option A : `search_name = search_name.replace(" ", "%") + "%"`
- option B : `search_name = "%" + search_name.replace(" ", "%") + "%"`

**Comment by jacquesfize** [comment]
L'option A me semble la plus cohérente.

**Comment by jpm-cbna** [comment]
Tu peux tester l'option B sur l'Atlas du SINP AURA : https://atlas.biodiversite-auvergne-rhone-alpes.fr/
Le champ en haut à droite permet de rechercher une commune de la région AURA avec l'option B, par exemple la fin de son nom. Si tu prends la commune "Saint-Étienne-de-Lugdarès", en tapant just "lugd" tu la trouves directement.

C'est d'ailleurs souvent la fin du nom de la commune qui est le plus intéressant. Il suffit de commencer à taper "Saint" ou "Saint Etienne" ou "Saint Laurent" pour se rendre compte qu'il y a un grand nombre de noms de communes qui commencent de la même façon.

**Comment by jacquesfize** [comment]
Je suis convaincu ! Va pour l'option B !

**Comment by jacquesfize** [comment]
Dans la version 1.5.4 de RefGeo
