### ISSUE TITLE
Ajout de la géométrie 4326 aux zonages

### ISSUE THREAD

**Issue by bouttier** [PnX-SI/RefGeo#6]
Actuellement, on ne stock que la géométrie au SRID local, et le geojson pré-calculé au SRID 4326, mais on ne stock pas la géométrie au SRID 4326.
C’est limitant :
- Impossibilité d’utiliser ``ST_Simplify``
- Même pour générer du geojson, avoir le geojson pré-calculé n’est pas le plus pratique, les outils étant plutôt prévu pour manipuler une géométrie

L’ajout du champs nécessite une attention particulière avec les triggers : si on met à jour la géom 4326, il faut recalculer la géom local et inversement, et il faut interdire de mettre à jour les 2 champs en même temps (?)

**Comment by camillemonchicourt** [comment]
OK pour moi.
Seule interrogation : cela va alourdir (beaucoup ?) la BDD.
A voir aussi si on met à jour dans les 2 sens, ou seulement geom_local > geom_4326, en indiquant bien de ne remplir/modifier que le geom_local ?

**Comment by camillemonchicourt** [comment]
Si on peut supprimer la colonne 'geojson_4326' c'est intéressant, mais il faudrait vérifier son usage et pourquoi on l'avait créée.

**Comment by bouttier** [comment]
Je n’ai trouvé nul endroit dans GeoNature où on l’utilise !

**Comment by camillemonchicourt** [comment]
Il est certainement utilisé dans la DEVELOP pour l'affichage agrégé des observations de la synthèse par maille.
Mais OK pour moi de le supprimer.

**Comment by lpofredc** [comment]
Une question un peu bêta, as-t-on vraiment besoin de conserver ces multiples champs geom. Les transformations à la volée (via `st_transform` et si besoin `st_asgeojson`) ne suffisent-ils pas pour les quelques cas de figure ou c'est utilisé ? D'autant plus qu'il tout à fait possible d'indexer un champ en utilisant `st_transform`:

```sql
CREATE INDEX idx_geom_4326_geomtable
  ON GeomTable
  USING gist
  (ST_Transform(geom, 4326));
```

Concernant ce point https://github.com/PnX-SI/RefGeo/issues/6#issuecomment-1339461709, depuis PG12 (PG11 est arrivé en fin de vie ce mois-ci), il y a la possibilité d'utiliser les colonnes autogénérées: https://www.postgresql.org/docs/current/ddl-generated-columns.html

**Comment by camillemonchicourt** [comment]
Surtout on se dit que si on refaisait la BDD aujourd'hui on ne stockerait que des géométrie en 4326, et on ne s'embêterait pas avec des géométries dans les projections locales (différentes selon les contextes) qu'on doit toujours reprojeter, etc... 
Et qui n'apportent à priori rien...

Par contre, pour le floutage des données sensibles on a identifié que si on doit reprojeter les zonages en 4326 avant de lancer des intersections, les performances sont multipliées entre 10 et 50 fois...

**Comment by bouttier** [comment]
- Effectivement on peut se mettre à utiliser les colonnes générées puisqu’on vise désormais Debian 11 et donc PG 13
- J’imagine qu’il s’agirait alors plutôt de calculer la geom local à partir de la geom 4326. Mais si on obtient les données directement en SRID local, on se retrouve à les convertir 2 fois, n’y a-t-il pas une perte de précision ici, ou est-elle acceptable ? Le trigger proposé dans #17 accepte l’un ou l’autre et fait la conversion dans le bon sens (tout comme l’import dans la synthèse, on ne sait pas à priori dans quel SRID on va recevoir les données).
- L’index sur le ST_Transform est intéressant, mais :
  - J’ai peur que lors d’un ST_Intersect, il faille quand même convertir les geom qui ont matché l’index, donc quand même plus lent, mais peut-être acceptable ?
  - On utilise également la geom_4326 pour pour renvoyer les zonages à la carte, donc difficile de s’en passer

On peut peut-être ouvrir un autre ticket pour étudier les impactes de la suppression de la geom local.

**Comment by camillemonchicourt** [comment]
A terme (un jour ? dans une V3 ?), on parlait de ne plus du tout avoir de geom_local, mais seulement des geom_4326.
Par contre si on n'en garde qu'un seul et qu'on calcule l'autre, je garderai le geom_local de base, car c'est celui qu'on remplit quand on importe les données IGN, les mailles INPN, ou qu'on met à jour son RefGeo avec QGIS. 
Faire l'inverse, je vois pas trop d'intérêt.
